/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mainframe;
import java.util.*;
import org.reflections.Reflections;
import org.reflections.scanners.SubTypesScanner;
import org.mainframe.Typo.Annotations.InitTypo;
import org.mainframe.Typo.TyposRunner;

//@InitTypo("org.mainframe")
public class HttpServer {
    
    public static void main(String[] args) {
     //  TyposRunner.run(HttpServer.class);
    }
}
